"""painapple-code: WebSocket bridge server for remote Claude Code clients.

Internal modules use absolute imports rooted at this package, e.g.
``from painapple_code.session_store import SessionStore``.

Two well-known paths:

* ``PACKAGE_DIR`` — the installed package directory, containing
  ``static/``, ``data/`` (strings/models/presets), and runtime
  ``tools/``. Resolves the same in editable installs and wheels;
  this is what server code should use for shipped assets.
* ``REPO_ROOT`` — the surrounding repo checkout (``parent.parent.parent``
  from this file). Only meaningful in editable/dev installs; use it for
  developer-only paths like ``tests/perf`` or the optional
  ``docs/features/`` triage data. In a wheel install this points
  somewhere under ``site-packages`` and should not be relied on.
"""

from pathlib import Path

PACKAGE_DIR: Path = Path(__file__).resolve().parent
REPO_ROOT: Path = PACKAGE_DIR.parent.parent

# _version.py is generated by setuptools-scm at build/install time (see
# pyproject.toml). Missing means an editable install in a tree where the
# build hook hasn't run yet — fall back rather than crashing imports.
try:
    from ._version import __version__
except ImportError:
    __version__ = "0.0.0+unknown"
