// Native iPadOS hooks for the web app:
//
//   1. Cmd+W / Cmd+Q routing — captures these chords before UIKit's system
//      scene-close / app-quit actions so we can decide what to do (close
//      a tab, dismiss the launcher popup, close just this scene, etc.)
//      instead of having the whole scene torn down or the app terminated
//      out from under the user.
//
//   2. Scene destruction bridge — exposes a `painappleCloseScene` script
//      message handler that calls UIApplication's
//      requestSceneSessionDestruction:options:errorHandler:. This is the
//      only API that actually tears down a UIWindowScene on iPadOS; Tauri's
//      WebviewWindow::close() and ::destroy() both silently no-op for
//      popup scenes (confirmed via the launcher popup's X button doing
//      nothing). launcher.js's closePopup talks to this handler so the X /
//      Esc / Cmd+W paths can all dismiss the popup. Cmd+Q goes straight
//      to the same destruction call without bouncing through JS.
//
// Why this file (and not Swift): Tauri/wry creates the WKWebView for us; we
// can't subclass it. class_replaceMethod swizzles WKWebView's instance
// methods in place — UIResponder's inherited defaults are untouched, so
// other responders aren't affected.
//
// Chord interception layers (defense in depth on iPadOS):
//
//   - pressesBegan:withEvent:: fires earlier than UIKeyCommand dispatch on
//     iOS 13.4+. Consuming the chord here (don't call super) prevents
//     UIKit's later scene-close / app-quit resolution from running at all.
//     This is the primary mechanism for Cmd+W — keyCommands +
//     wantsPriorityOverSystemBehavior alone wasn't firing reliably on
//     chord-spawned popup scenes.
//
//   - keyCommands + wantsPriorityOverSystemBehavior=YES: backup for the
//     rare case where pressesBegan doesn't fire (iOS < 13.4, WKWebView
//     not the focused responder).
//
// Cmd+Q on iPad is left alone — iPadOS routes it through SpringBoard at
// a level that neither pressesBegan nor a UIApplication menu-swizzle
// (removing UIMenuQuit + reinserting our own command) can intercept.
// Tried both; both compile but get bypassed. macOS handles Cmd+Q via the
// Tauri menu in lib.rs.
//
// JS dispatch precedence for Cmd+W:
//   window.app.closeActiveTab          (session window — close active tab)
//   window.__painapple_close_window__  (any launcher window — dismiss it)
//   no-op                              (page with neither hook)
//
// Cmd+Q always closes the current scene — never a tab. Routes straight to
// painapple_destroyScene (no JS round-trip needed, since no page-level
// hook needs first dibs).
//
// File location: kept outside `gen/apple/` (which is gitignored and
// regenerated by `tauri ios init`) so it survives regeneration. The
// `scripts/ios-postinit.sh` Patch 4 copies it into the iOS target's
// Sources/ tree on every build.

#import <UIKit/UIKit.h>
#import <WebKit/WebKit.h>
#import <objc/runtime.h>

// ─── Scene destruction bridge ──────────────────────────────────────────

@interface WKWebView (PainappleSceneClose)
- (void)painapple_destroyScene;
@end

@implementation WKWebView (PainappleSceneClose)

- (void)painapple_destroyScene {
    UIWindow *win = self.window;
    if (![win isKindOfClass:[UIWindow class]]) return;
    UIWindowScene *scene = win.windowScene;
    if (![scene isKindOfClass:[UIWindowScene class]]) return;
    UISceneSession *session = scene.session;
    if (!session) return;
    UISceneDestructionRequestOptions *opts = [UISceneDestructionRequestOptions new];
    [[UIApplication sharedApplication]
        requestSceneSessionDestruction:session
                               options:opts
                          errorHandler:^(NSError *err) {
                              NSLog(@"painapple: scene destruction failed: %@", err);
                          }];
}

@end

// Singleton message handler — WKWebViewConfiguration retains it; we keep
// one shared instance because the message itself carries `message.webView`
// so we don't need per-webview state.
@interface PainappleSceneCloseHandler : NSObject <WKScriptMessageHandler>
+ (instancetype)shared;
@end

@implementation PainappleSceneCloseHandler

+ (instancetype)shared {
    static PainappleSceneCloseHandler *instance;
    static dispatch_once_t once;
    dispatch_once(&once, ^{ instance = [PainappleSceneCloseHandler new]; });
    return instance;
}

- (void)userContentController:(WKUserContentController *)controller
      didReceiveScriptMessage:(WKScriptMessage *)message {
    [message.webView painapple_destroyScene];
}

@end

// ─── Cmd+W / Cmd+Q routing ─────────────────────────────────────────────

static NSArray<UIKeyCommand *> *(*painapple_originalKeyCommands)(id, SEL) = NULL;
static void (*painapple_originalPressesBegan)(id, SEL, NSSet *, UIPressesEvent *) = NULL;
static void (*painapple_originalDidMoveToWindow)(id, SEL) = NULL;

// Match Cmd+<letter> with no other modifiers. Letter compare is
// case-insensitive because Shift isn't required and `charactersIgnoringModifiers`
// can deliver either case depending on Caps Lock state.
static BOOL painapple_isCmdLetter(UIKey *key, NSString *letter) {
    if (!key) return NO;
    if (@available(iOS 13.4, *)) {
        NSString *chars = key.charactersIgnoringModifiers;
        if ([chars caseInsensitiveCompare:letter] != NSOrderedSame) return NO;
        UIKeyModifierFlags mods = key.modifierFlags;
        if (!(mods & UIKeyModifierCommand)) return NO;
        if (mods & (UIKeyModifierShift | UIKeyModifierAlternate | UIKeyModifierControl)) return NO;
        return YES;
    }
    return NO;
}

static void painapple_dispatchCloseW(WKWebView *self) {
    NSString *js =
        @"if(window.app&&typeof window.app.closeActiveTab==='function'){window.app.closeActiveTab();}"
        @"else if(typeof window.__painapple_close_window__==='function'){window.__painapple_close_window__();}";
    [self evaluateJavaScript:js completionHandler:nil];
}

static void painapple_pressesBegan_impl(WKWebView *self, SEL _cmd, NSSet<UIPress *> *presses, UIPressesEvent *event) {
    if (@available(iOS 13.4, *)) {
        for (UIPress *press in presses) {
            if (painapple_isCmdLetter(press.key, @"w")) {
                painapple_dispatchCloseW(self);
                return; // Don't call super → press is consumed, scene-close never fires.
            }
            if (painapple_isCmdLetter(press.key, @"q")) {
                [self painapple_destroyScene];
                return; // Don't call super → press is consumed, app-quit never fires.
            }
        }
    }
    if (painapple_originalPressesBegan) {
        painapple_originalPressesBegan(self, _cmd, presses, event);
    }
}

static NSArray<UIKeyCommand *> *painapple_keyCommands_impl(WKWebView *self, SEL _cmd) {
    UIKeyCommand *closeTab = [UIKeyCommand
        keyCommandWithInput:@"w"
        modifierFlags:UIKeyModifierCommand
        action:@selector(painapple_closeActiveTab:)];
    UIKeyCommand *closeWindow = [UIKeyCommand
        keyCommandWithInput:@"q"
        modifierFlags:UIKeyModifierCommand
        action:@selector(painapple_closeWindow:)];
    if (@available(iOS 15.0, *)) {
        closeTab.wantsPriorityOverSystemBehavior = YES;
        closeWindow.wantsPriorityOverSystemBehavior = YES;
    }
    NSArray<UIKeyCommand *> *ours = @[closeTab, closeWindow];
    NSArray<UIKeyCommand *> *orig = painapple_originalKeyCommands
        ? painapple_originalKeyCommands(self, _cmd)
        : nil;
    if (orig.count) {
        return [ours arrayByAddingObjectsFromArray:orig];
    }
    return ours;
}

// Lazy-registers the scene-close script message handler the first time
// the webview is attached to a window. didMoveToWindow is the earliest
// hook with a guaranteed valid configuration; doing it in initWithFrame:
// would race against wry's own configuration setup.
static void painapple_didMoveToWindow_impl(WKWebView *self, SEL _cmd) {
    if (painapple_originalDidMoveToWindow) {
        painapple_originalDidMoveToWindow(self, _cmd);
    }
    if (!self.window) return;
    static char kHandlerInstalledKey;
    if (objc_getAssociatedObject(self, &kHandlerInstalledKey)) return;
    WKUserContentController *cc = self.configuration.userContentController;
    if (!cc) return;
    [cc addScriptMessageHandler:[PainappleSceneCloseHandler shared]
                           name:@"painappleCloseScene"];
    objc_setAssociatedObject(self, &kHandlerInstalledKey, @YES, OBJC_ASSOCIATION_RETAIN);
}

@interface WKWebView (PainappleKeyCommands)
- (void)painapple_closeActiveTab:(UIKeyCommand *)cmd;
- (void)painapple_closeWindow:(UIKeyCommand *)cmd;
@end

@implementation WKWebView (PainappleKeyCommands)

+ (void)load {
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        Class cls = [WKWebView class];

        SEL pressesSel = @selector(pressesBegan:withEvent:);
        Method pressesExisting = class_getInstanceMethod(cls, pressesSel);
        if (pressesExisting) {
            painapple_originalPressesBegan =
                (void (*)(id, SEL, NSSet *, UIPressesEvent *))method_getImplementation(pressesExisting);
        }
        class_replaceMethod(cls, pressesSel, (IMP)painapple_pressesBegan_impl, "v@:@@");

        SEL keySel = @selector(keyCommands);
        Method keyExisting = class_getInstanceMethod(cls, keySel);
        if (keyExisting) {
            painapple_originalKeyCommands =
                (NSArray<UIKeyCommand *> *(*)(id, SEL))method_getImplementation(keyExisting);
        }
        class_replaceMethod(cls, keySel, (IMP)painapple_keyCommands_impl, "@@:");

        SEL didMoveSel = @selector(didMoveToWindow);
        Method didMoveExisting = class_getInstanceMethod(cls, didMoveSel);
        if (didMoveExisting) {
            painapple_originalDidMoveToWindow =
                (void (*)(id, SEL))method_getImplementation(didMoveExisting);
        }
        class_replaceMethod(cls, didMoveSel, (IMP)painapple_didMoveToWindow_impl, "v@:");
    });
}

- (void)painapple_closeActiveTab:(UIKeyCommand *)cmd {
    painapple_dispatchCloseW(self);
}

- (void)painapple_closeWindow:(UIKeyCommand *)cmd {
    [self painapple_destroyScene];
}

@end
