#!/usr/bin/env python3
"""Density-mode CSS generator — the "creator" for the layout token system.

Single source of truth: tools/design-tokens.yaml (current values) or any
spec file with the same schema, passed via --spec. The
generator (re)writes the LAYOUT MODES section of
src/painapple_code/static/css/00-variables.css, so redesigning the three
density modes = edit YAML → regenerate → capture the gallery to preview.

Usage:
    tools/gen_density_css.py                          # print generated CSS
    tools/gen_density_css.py --diff                   # diff vs current file
    tools/gen_density_css.py --write                  # splice into 00-variables.css
    tools/gen_density_css.py --spec tools/my-redesign.yaml --emit /tmp/p.css
                                                      # standalone override file
                                                      # (for gallery.sh capture --inject-css)
    tools/gen_density_css.py --check                  # exit 1 if file out of sync

The spliced region is everything from the LAYOUT MODES banner comment to the
end of the file — the hand-maintained sections above (colors, fonts, radius,
z-index) are never touched.
"""

import argparse
import difflib
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CSS_FILE = REPO / "src/painapple_code/static/css/00-variables.css"
DEFAULT_SPEC = Path(__file__).resolve().parent / "design-tokens.yaml"

BANNER = """/* ═══════════════════════════════════════════════════════════════════
   LAYOUT MODES: compact | normal | spacious
   Set via <html data-layout="...">. Two var families respond:
     --sp-N   numeric spacing scale — N is the pixel value in NORMAL mode.
              Use for any whitespace that should breathe with density:
              padding, gap, margin, row height. Do NOT use for alignment
              geometry, popup positioning offsets, or icon dimensions.
     --layout-*  semantic tokens for the core chat surfaces (header,
              messages, input, tool blocks).
   Full rules: docs-ai/layout-density-guide.md

   @generated by tools/gen_density_css.py from %SPEC% — edit the YAML
   and regenerate; do not hand-edit below this banner.
   ═══════════════════════════════════════════════════════════════════ */
"""


def px(v):
    # ints are px; floats (line-heights) stay unitless; strings pass through
    return f"{v}px" if isinstance(v, int) else str(v)


def render_mode(name, spec, mode):
    sel = ":root" if name == "normal" else f'[data-layout="{name}"]'
    lines = [f"/* {mode.get('comment', name)} */", sel + " {"]
    for tok, val in zip(spec["sp_tokens"], mode["sp"]):
        lines.append(f"    --sp-{tok}: {px(val)};")
    lines.append("")
    for key, val in mode["layout"].items():
        lines.append(f"    --layout-{key}: {val if isinstance(val, str) else px(val)};")
    lines.append("}")
    return "\n".join(lines)


def generate(spec, spec_name):
    for name, mode in spec["modes"].items():
        assert len(mode["sp"]) == len(spec["sp_tokens"]), \
            f"mode {name}: sp list length != sp_tokens length"
        # sanity: warn on non-monotonic scales (token collisions are the
        # historic bug — sp-12 == sp-14 in old compact)
        pairs = list(zip(spec["sp_tokens"], mode["sp"]))
        for (t1, v1), (t2, v2) in zip(pairs, pairs[1:]):
            if v2 < v1:
                print(f"warning: {name} --sp-{t2} ({v2}) < --sp-{t1} ({v1})",
                      file=sys.stderr)
            elif v2 == v1 and t1 >= 5:
                print(f"warning: {name} token collision --sp-{t1} == --sp-{t2} "
                      f"({v1}px) — hierarchy authored in normal collapses here",
                      file=sys.stderr)
    body = "\n\n".join(
        render_mode(name, spec, spec["modes"][name])
        for name in ("normal", "compact", "spacious"))
    return BANNER.replace("%SPEC%", spec_name) + "\n" + body + "\n"


def splice(css_text, generated):
    m = re.search(r"/\* ═+\n\s+LAYOUT MODES", css_text)
    if not m:
        sys.exit("could not find the LAYOUT MODES banner in 00-variables.css")
    return css_text[:m.start()] + generated


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--spec", default=str(DEFAULT_SPEC))
    ap.add_argument("--write", action="store_true", help="splice into 00-variables.css")
    ap.add_argument("--diff", action="store_true", help="show diff vs current file")
    ap.add_argument("--check", action="store_true", help="exit 1 if out of sync")
    ap.add_argument("--emit", metavar="FILE",
                    help="write standalone override CSS (for gallery --inject-css)")
    args = ap.parse_args()

    spec_path = Path(args.spec)
    spec = yaml.safe_load(spec_path.read_text())
    generated = generate(spec, f"tools/{spec_path.name}")

    if args.emit:
        # Standalone: just the three blocks, no banner splice needed — an
        # injected <style> later in the document wins the cascade at equal
        # specificity, so this previews a proposal without touching source.
        Path(args.emit).write_text(generated)
        print(f"wrote {args.emit}")
        return

    current = CSS_FILE.read_text()
    new = splice(current, generated)

    if args.write:
        CSS_FILE.write_text(new)
        print(f"wrote {CSS_FILE}")
    elif args.diff or args.check:
        diff = list(difflib.unified_diff(
            current.splitlines(keepends=True), new.splitlines(keepends=True),
            fromfile="current", tofile=f"generated({spec_path.name})"))
        sys.stdout.writelines(diff)
        if args.check and diff:
            sys.exit(1)
        if not diff:
            print("in sync")
    else:
        print(generated)


if __name__ == "__main__":
    main()
